# Site settings
title: "Fernando A. Galdino Resume"
description: "A resume for Fernando Galdino on GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Fernando A. Galdino"
resume_title:                   "Enterprise Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "fdagald@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "Please, ask me"
resume_contact_address:         "São Paulo, SP, Brazil"

resume_header_contact_info:     "fdagald@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>This is the journey of Fernando Galdino, a person who embodies the principles of exploration, adaptability, and collaboration. With a proven track record of success, I bring a unique blend of visionary thinking, strategic decision-making, and unwavering commitment to achieving extraordinary outcomes.</p>"
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/fdagaldino/resume-template"
  resume_twitter_url:           "http://twitter.com/fdagaldino"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/fdagaldino"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://fdagaldino.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
